### ISSUE TITLE
got RpcRetryingCaller: Call exception, when running the program

### ISSUE THREAD

**Issue by ghost** [zeyuanxy/spark-hbase-bulk-loading#2]
1 INFO RpcRetryingCaller: Call exception, tries=12, retries=35, started=108774 ms ago, cancelled=false, msg=row '' on table 'reg_profile' at region=reg_profile,,1497838472245.e158680961a05c518099e5e43e62978a., hostname=bd-qa-hadoop-68,60020,1495433128771, seqNum=5

My Spark 片段：
    val hadoopConf: Configuration = new Configuration()
//    hadoopConf.set("hbase.zookeeper.quorum", "bd-dev-hadoop2-144,bd-dev-hadoop2-145,bd-dev-hadoop2-146")
    hadoopConf.set("hbase.zookeeper.quorum", "bd-qa-hadoop-67,bd-qa-hadoop-68,bd-qa-hadoop-69,bd-qa-hadoop-70")
    hadoopConf.set("hbase.zookeeper.property.clientPort", "2181")
    hadoopConf.set(TableOutputFormat.OUTPUT_TABLE, tableName)
    hadoopConf.set("zookeeper.znode.parent", "/hbase")

**Comment by zeyuanxy** [comment]
I don't think this is related with my library, I guess it may be caused by network crash in your cluster.
